=== bbrando021/ContextAwareSOA_in_IoT/Schema/Thing_XML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"><!--XML Schema for the architecture of the Thing-->
	<xsd:element name="Thing">
		<xsd:complexType>
			<xsd:sequence><!--OBJECT-->
				<xsd:element name="Object">
					<xsd:complexType>
						<xsd:sequence><!--a functional requirement is any requirement which specifies what the system should do.-->
							<xsd:element name="FunctionalProperties">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="objectName" type="xsd:string"/>
										<xsd:element name="brand" type="xsd:string"/>
										<xsd:element name="model" type="xsd:string"/>
										<xsd:element name="objectDescription" type="xsd:string"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element><!--non-functional requirement will describe how a system should behave and what limits there are on its functionality.-->
							<xsd:element name="Non-FunctionalProperties">
								<xsd:complexType>
									<xsd:sequence><!--Can be dynamic or static, will consist of user defined elements such as location, 
									and other context that uniquely defines a specific object-->
										<xsd:element name="contextOfObject">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:sequence minOccurs="0" maxOccurs="unbounded">
														<xsd:element name="tag" type="xsd:string"/>
														<xsd:element name="description" type="xsd:string"/>
													</xsd:sequence>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element><!--These are properties of the Thing, these will never change-->
										<xsd:element name="propertiesOfObject">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:sequence minOccurs="0" maxOccurs="unbounded">
														<xsd:element name="tag" type="xsd:string"/>
														<xsd:element name="description" type="xsd:string"/>
													</xsd:sequence>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element><!--SERVICE-->
				<xsd:element name="Service">
					<xsd:complexType>
						<xsd:sequence><!--a functional requirement is any requirement which specifies what the system should do.-->
							<xsd:element name="FunctionalProperties" minOccurs="0">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="serviceName" minOccurs="0" type="xsd:string"/>
										<xsd:element name="serviceDescription" minOccurs="0" type="xsd:string"/>
										<xsd:element name="input" minOccurs="0">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:sequence minOccurs="0" maxOccurs="unbounded">
														<xsd:element name="name" type="xsd:string"/>
														<xsd:element name="type" type="xsd:string"/>
													</xsd:sequence>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
										<xsd:element name="output" minOccurs="0" type="xsd:string"/>
										<xsd:element name="exampleOutput" minOccurs="0" type="xsd:string"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element><!--non-functional requirement will describe how a system should behave and what limits there are on its functionality.-->
							<xsd:element name="Non-FunctionalProperties" minOccurs="0">
								<xsd:complexType>
									<xsd:sequence><!--How much will one use, or multiple uses of this service cost-->
										<xsd:element name="cost" minOccurs="0" type="xsd:decimal"/><!--Can be dynamic or static, will consist of user defined elements such as location, 
									and other context that uniquely defines a specific service-->
										<xsd:element name="contextOfService" minOccurs="0">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:sequence minOccurs="0" maxOccurs="unbounded">
														<xsd:element name="tag" type="xsd:string"/>
														<xsd:element name="description" type="xsd:string"/>
													</xsd:sequence>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element><!--These are properties of the Service, these will never change-->
										<xsd:element name="propertiesOfService" minOccurs="0">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:sequence minOccurs="0" maxOccurs="unbounded">
														<xsd:element name="tag" type="xsd:string"/>
														<xsd:element name="description" type="xsd:string"/>
													</xsd:sequence>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
										<xsd:element name="constraints">
											<xsd:complexType>
												<xsd:sequence><!--Can this service utilize other services to complete more complex requests--><!--XXXXXXXX-->
													<xsd:element name="interoperability" minOccurs="0">
														<xsd:complexType>
															<xsd:sequence>
																<xsd:element name="boolean" type="xsd:boolean"/>
																<xsd:element name="otherServiceName" type="xsd:string"/>
															</xsd:sequence>
														</xsd:complexType>
													</xsd:element><!--How secure is the data that is being used and manipulated--><!--XXXXXXXX-->
													<xsd:element name="security" minOccurs="0" type="xsd:string"/><!--Can this service scale to handle multiple requests,the ability of this service to handle growth efficiently--><!--XXXXXXXX-->
													<xsd:element name="scalability" minOccurs="0" type="xsd:integer"/>
														<!--Describes how fast, accurate, etc this service is--><!--XXXXXXXX-->
													<xsd:element name="performance" minOccurs="0">
														<xsd:complexType>
															<xsd:sequence>
																<xsd:element name="time" type="xsd:decimal"/>
																<xsd:element name="units" type="xsd:string"/>
															</xsd:sequence>
														</xsd:complexType>
													</xsd:element>
													<!--When is this service available. Should be calculated using this formula: 
												(MeanTimeBetweenFailure / MTBF + MeanTimeToRecovery) * 100    
												MTBF is (Hours / Failure Count) ... MTTR is (Repair Hours / Failure Counts)-->
													<xsd:element name="availability" minOccurs="0" type="xsd:decimal"/><!--How and where will the requester gain access to this service-->
													<xsd:element name="accessibility" minOccurs="0" type="xsd:string"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element><!--SEARCH AND MATCHING TAGS-->
				<xsd:element name="searchTags">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="tag" minOccurs="0" maxOccurs="unbounded"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== bbrando021/ContextAwareSOA_in_IoT/Publisher_Requester_Examples/ComputerThing.xml
<?xml version='1.0' encoding='UTF-8'?>
<Thing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\Brandon\Desktop\Research\XML\Thing_XML.xsd">
	<Object>
		<FunctionalProperties>
			<objectName>Computer 123B</objectName>
			<brand>Mac</brand>
			<model>Laptop</model>
			<objectDescription>Computer Usage Availability</objectDescription>
		</FunctionalProperties>
		<Non-FunctionalProperties>
			<contextOfObject>
				<tag>Yes</tag>
				<description>Computer Available</description>
			</contextOfObject>
			<propertiesOfObject>
				<tag>School</tag>
				<description>Penn State Behrend</description>
				<tag>Building</tag>
				<description>Burke</description>
				<tag>Floor</tag>
				<description>Second Floor</description>
				<tag>Room</tag>
				<description>153</description>
				<tag>Printer</tag>
				<description>True</description>
				<tag>Dual Monitor</tag>
				<description>True</description>
			</propertiesOfObject>
		</Non-FunctionalProperties>
	</Object>
	<Service>
	<!--NOTHING HERE BECAUSE THERE IS NO REMOTE SERVICE-->
	</Service>
	<searchTags>
		<tag>Computer</tag>
		<tag>Classroom</tag>
		<tag>Available</tag>
		<tag>Homework</tag>
		<tag>Study</tag>
		<tag>Lab</tag>
		<tag>Projector</tag>
	</searchTags>
</Thing>

=== bbrando021/ContextAwareSOA_in_IoT/Publisher_Requester_Examples/ParkingSpotThing.xml
<?xml version='1.0' encoding='UTF-8'?>
<Thing xsi:noNamespaceSchemaLocation="C:\Users\Brandon\Desktop\Research\XML\Thing_XML.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Object>
		<FunctionalProperties>
			<objectName>Randy's Parking Lot - Space 12</objectName>
			<brand>Accu-right Sensor</brand>
			<model>12vb-light</model>
			<objectDescription>Full size parking spot</objectDescription>
		</FunctionalProperties>
		<Non-FunctionalProperties>
			<contextOfObject>
				<tag>Yes</tag>
				<description>Spot Open</description>
			</contextOfObject>
			<propertiesOfObject>
				<tag>Spot Size</tag>
				<description>Regular</description>
				<tag>Covered</tag>
				<description>Yes</description>
				<tag>Access</tag>
				<description>Parking Pass</description>

			</propertiesOfObject>
		</Non-FunctionalProperties>
	</Object>
	<Service>
		<FunctionalProperties>
			<serviceName>Parking Spot Finder</serviceName>
			<serviceDescription>This service directs you to the parking spot</serviceDescription>
			<input>
				<name>Location</name>
				<type>Requesters Coordinates</type>
				<name>vehicle Info</name>
				<type>Type of Car</type>
			</input>
			<output>Routes to Spot</output>
		</FunctionalProperties>
		<Non-FunctionalProperties>
			<cost>0.25</cost>
			<contextOfService>
				<tag>Location</tag>
				<description>Coordinates of Spot</description>
			</contextOfService>
			<constraints>
				<interoperability>
					<boolean>false</boolean>
					<otherServiceName></otherServiceName>
				</interoperability>
				<security>User must make account and enter credientials before using service</security>
				<scalability>1</scalability>
				<performance>
					<time>24</time>
					<units>minutes</units>
				</performance>
				<availability>99.9</availability>
				<accessibility>https://play.google.com/store/apps/details?id=parking_spot</accessibility>
			</constraints>
		</Non-FunctionalProperties>
	</Service>
	<searchTags>
		<tag>Parking</tag>
		<tag>Car</tag>
		<tag>Parking Lot</tag>
		<tag>Space</tag>
		<tag>Available</tag>
		<tag>Navigation</tag>
	</searchTags>
</Thing>

=== bbrando021/ContextAwareSOA_in_IoT/Publisher_Requester_Examples/Computer1.xml
<?xml version='1.0' encoding='UTF-8'?>
<Thing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\Brandon\Desktop\Research\XML\Thing_XML.xsd">
	<Object>
		<FunctionalProperties>
			<objectName>Computer HWT50112</objectName>
			<brand>Dell</brand>
			<model>Envy 11223-cv3</model>
			<objectDescription>Computer Usage Availability</objectDescription>
		</FunctionalProperties>
		<Non-FunctionalProperties>
			<contextOfObject>
				<tag>No</tag>
				<description>Computer Available</description>
			</contextOfObject>
			<propertiesOfObject>
				<tag>School</tag>
				<description>Penn State Behrend</description>
				<tag>Building</tag>
				<description>Burke</description>
				<tag>Floor</tag>
				<description>Third Floor</description>
				<tag>Room</tag>
				<description>206</description>
				<tag>Printer</tag>
				<description>False</description>
				<tag>Dual Monitor</tag>
				<description>False</description>
			</propertiesOfObject>
		</Non-FunctionalProperties>
	</Object>
	<Service/>
	<searchTags>
		<tag>Computer</tag>
		<tag>Available</tag>
		<tag>Homework</tag>
		<tag>Study</tag>
		<tag>Lecture</tag>
	</searchTags>
</Thing>

=== bbrando021/ContextAwareSOA_in_IoT/Publisher_Requester_Examples/Computer3.xml
<?xml version='1.0' encoding='UTF-8'?>
<Thing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\Brandon\Desktop\Research\XML\Thing_XML.xsd">
	<Object>
		<FunctionalProperties>
			<objectName>Computer HWT1242-LAB</objectName>
			<brand>HP</brand>
			<model>Pavilion</model>
			<objectDescription>Computer Usage Availability</objectDescription>
		</FunctionalProperties>
		<Non-FunctionalProperties>
			<contextOfObject>
				<tag>Yes</tag>
				<description>Computer Available</description>
			</contextOfObject>
			<propertiesOfObject>
				<tag>School</tag>
				<description>Penn State Behrend</description>
				<tag>Building</tag>
				<description>Burke</description>
				<tag>Floor</tag>
				<description>Second Floor</description>
				<tag>Room</tag>
				<description>153</description>
				<tag>Printer</tag>
				<description>True</description>
				<tag>Dual Monitor</tag>
				<description>True</description>
			</propertiesOfObject>
		</Non-FunctionalProperties>
	</Object>
	<Service>
	<!--NOTHING HERE BECAUSE THERE IS NO REMOTE SERVICE-->
	</Service>
	<searchTags>
	<tag>Projector</tag>
	<tag>Study</tag>
	<tag>Class</tag>
	<tag>Classroom</tag>
	<tag>Available</tag>
	<tag>Availability</tag>
	<tag>Open</tag>
	<tag>Room</tag>
	
	</searchTags>
</Thing>
